# Generated by Django 3.2 on 2021-06-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210606_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='intro_image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس محصولات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='نام'),
        ),
    ]
