BBBBBBB BBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBBBBBBB
    XXXX XXXXXXX
BBBBBBBB
BBBBB BBBBBBB

    XXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXX XXXXXX
                XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                XXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX
                        
                    XXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXX
                        XXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
                        
                    XXXXXX
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
BBBBBBBB
