# Generated by Django 3.2 on 2021-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس مقدمه پست'),
        ),
    ]
